### ISSUE TITLE
Language Strings

### ISSUE THREAD

**Issue by brianteeman** [j2commerce/j2cart#25]
I propose the following improvements

1. Language strings that can be found in core joomla eg administrator\language\en-GB\joomla.ini should be used instead of duplicating them in component language files. Not only will this reduce the number of strings that translators need to work on it will enforce consistency with core joomla.

2. Language strings should not be repeated with different constants eg    
   20: J2STORE_SELECT_OPTION="-- Select --"
   52: J2STORE_ADDTOCART_SELECT="-- Select --"
  667: J2STORE_SELECT_STATE="-- Select --"

3. Language string constants should use consistent prefixes. This will make future development much easier and make it easier to find if a language string value already exists. language\backend\en-GB\en-GB.com_j2store.ini has strings starting with
J2STORE_
COM_J2STORE_
MOD_J2STORE_
PLG_J2STORE_

There are also some strings which I assume are overrides and may have consequences outside of the component eg
COM_CONTENT_FEATURED_ORDER="Featured products (articles) first"

**Comment by j2commerce** [comment]
Definitely needs some cleanup there... Thanks Brian for the heads up.

**Comment by brianteeman** [comment]
Replaced by #69
