### ISSUE TITLE
Copyright Notice

### ISSUE THREAD

**Issue by brianteeman** [j2commerce/j2cart#36]
As you know you can't change the licence of any files but you can and should update the copyright.

I am not an expert on this at all and I am not a lawyer but I would suggest that you ADD your copyright to all the files. See example below. This way you are clearly indicating that changes made in 2024 are your copyright and you are not removing the existing copyright of Ramesh etc Someone can use github then if they want to see which lines etc were changed when.

```
/**
 * @package J2Store
 * @copyright Copyright (c)2014-17 Ramesh Elamathi / J2Store.org
 * @copyright Copyright (c) 2024 J2Commerce
 * @license GNU GPL v3 or later
 */
```
 
 Some of the plugins and modules have slightly different copyright headers but the principle is the same.

**Comment by j2commerce** [comment]
We opted for:

`
/**
 * @copyright Copyright (C) 2014-2019 Weblogicx India. All rights reserved.
 * @copyright Copyright (C) 2024 J2Commerce, Inc. All rights reserved.
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 * @author Ramesh Elamathi (weblogicxindia.com)
 * @author Adam Melcher adam@j2commerce.com
 * @author Olivier Buisard olivier@j2commerce.com
 * @website https://www.j2commerce.com
 */
`

**Comment by brianteeman** [comment]
The only problem with that is when do you add a new @author

**Comment by newlinewebdesign** [comment]
what would you recommend? I also notice the original example is @license GNU GPL v3 or later

is this what we should be using instead of the one included in the original copyright? 
(@license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL)

**Comment by brianteeman** [comment]
IANAL

The original repo is marked as GPL3
The original component is marked as GPL3
https://github.com/J2Store4/j2store4/blob/0031b53a06966e14cb71fce07e6f3fd090dd69bc/com_j2store.xml#L10

725 files are marked as GPL3 or later
102 files are marked as GPL2 - they are some of the older files 

Based on the state of the original repo I would suggest that the files marked as GPL2 were done in error (or were missed when the newer copyright was set as GPL3) as the intent was clearly to make j2store GPL3 or later

**You definitely cannot change something marked as GPL3 to GPL2**

For the files marked as GPL2 you can either
- treat it as an error and change them to gpl3 or later
- ask ramesh if you can change them to gpl3 or later
- leave those files as GPL2 but keep everything else as GPL3 or later
- ask advice of someone else eg @nikosdion

I definitely would not be adding @author

**Comment by newlinewebdesign** [comment]
@brianteeman so to clarify:
/**
 * @copyright Copyright (C) 2014-2019 Weblogicx India. All rights reserved.
 * @copyright Copyright (C) 2024 J2Commerce, Inc. All rights reserved.
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL  
 * @author Ramesh Elamathi (weblogicxindia.com)
 * @website https://www.j2commerce.com
 */
 
 or (depending on gpl version) should be fine?
/**
 * @copyright Copyright (C) 2014-2019 Weblogicx India. All rights reserved.
 * @copyright Copyright (C) 2024 J2Commerce, Inc. All rights reserved.
 * @license GNU GPL v3 or later
 * @author Ramesh Elamathi (weblogicxindia.com)
 * @website https://www.j2commerce.com
 */

**Comment by brianteeman** [comment]
except I would not be using the @ author

**Comment by newlinewebdesign** [comment]
perfect. thank you for clearing up some of the fog

**Comment by nikosdion** [comment]
The best source for what is allowed when mixing licenses is [the GNU FAQ](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) and its handy table. I do agree with @brianteeman that your current mix of GPLv2-only and GPLv3-or-later files is incompatible. It may not create a licensing issue _for you_, but it probably creates one for your users. It's best to mark this as an error, and retroactively license these files as GPLv3-or-later going back to the first version of your extension released under that license.

Regarding author attribution, it's a minefield. I prefer to include unaltered source code, ideally using a package manager (Composer or NPM), thereby completely sidestepping the issue of what to do with attribution.

**Comment by j2commerce** [comment]
Thank you Brian @brianteeman and Nicholas @nikosdion for the advice.
