### ISSUE TITLE
Standard shipping methods not being displayed when state is published.

### ISSUE THREAD

**Issue by TLWebdesign** [j2commerce/j2cart#56]
Hi,

i have a J2 store site and it does not show the published items on this url:

https://domain.nl/administrator/index.php?option=com_j2store&view=shipping&task=view&id=10630

It will only show when the state is unpublished.
See attached screenshot. in the DB there is a id with 1 and 3. But the table starts with 4. That is the first one that is unpublished. 

<img width="1423" alt="Scherm­afbeelding 2024-10-29 om 13 01 47" src="https://github.com/user-attachments/assets/bf4cf1b7-25aa-4554-9ee3-dce9139d9004">

**Comment by TLWebdesign** [comment]
I'm not very familiar with J2Store code but it seems some sort of filtering is broken in Joomla 5.1.4. I made a PR to fix the symptom but i'm not sure this is the cause of the problem tho.

**Comment by brianteeman** [comment]
Hannes broke a lot of the filtering in j5.x so it may be related

**Comment by j2commerce** [comment]
It looks like a legitimate issue. When the filter is not set, the query does not check the published value and therefore can return all states.
