### ISSUE TITLE
Remove code used in test blocks (when JVERSION < 3.999 for instance)

### ISSUE THREAD

**Issue by j2commerce** [j2commerce/j2cart#74]
Admin models/views/controllers
- [ ] app
- [ ] apps
- [ ] appstores
- [ ] carts
- [ ] configuration
- [ ] countries
- [ ] coupon
- [ ] cpanel
- [ ] crons
- [ ] currencies
- [ ] customer
- [ ] customers
- [ ] customfield
- [ ] emailtemplate
- [ ] eupdates
- [ ] filtergroup
- [ ] geozone
- [ ] inventories
- [ ] invoicetemplate
- [ ] length
- [ ] manufacturers
- [ ] option
- [ ] order
- [ ] orders
- [ ] orderstatuses
- [ ] payments
- [ ] postconfig
- [ ] productbase
- [ ] product
- [ ] products
- [ ] queues
- [ ] report
- [ ] reports
- [ ] shippings
- [ ] shippingtroubles
- [ ] taxprofile
- [ ] taxrate
- [ ] vendors
- [ ] voucher
- [ ] weights
- [ ] zones

Other admin
- [ ] models/fields
- [ ] models/behaviors
- [ ] helpers
- [ ] library

Site models/views/controllers
- [ ] carts
- [ ] checkout
- [ ] myprofile
- [ ] product
- [ ] products
- [ ] producttags
- [ ] vendor

Admin modules
- [ ] chart
- [ ] menu
- [ ] orders
- [ ] stats
- [ ] stats_mini

Site modules
- [ ] cart
- [ ] currency

Content plugins
- [ ] j2store

Finder plugins
- [ ] j2store

Installer plugins
- [ ] j2store

j2store plugins
- [ ] app-bootstrap3
- [ ] app-bootstrap4
- [ ] app-bootstrap5
- [ ] app_currencyupdater
- [ ] app_diagnostics
- [ ] app_flexivariable
- [ ] app_localization_data
- [ ] app_schemaproducts
- [ ] payment_banktransfer
- [ ] payment_cash
- [ ] payment_moneyorder
- [ ] payment_paypal
- [ ] payment_sagepayform
- [ ] report_itemised
- [ ] report_products
- [ ] shipping_free
- [ ] shipping_standard

search plugins
- [ ] j2store

system plugins
- [ ] j2canonical
- [ ] j2pagecache
- [ ] j2store

user plugins
- [ ] j2userregister

**Comment by brianteeman** [comment]
I have been meaning to ask about this. I thought at first it could be completely removed but then I read the migration instructions and it looks like everything in this release needs to work on j3 as well because the migration to j2storev4 takes place before the upgrade to j4 so it has to stay and can only be removed in a future version which after a user has migrated to j4

**Comment by j2commerce** [comment]
Totally accurate, I will close this issue and will move that task to the J2Commerce extension.
