### ISSUE TITLE
Remove index.html

### ISSUE THREAD

**Issue by j2commerce** [j2commerce/j2cart#76]
Keep index.html files in empty folders.

Admin models/views/controllers
- [ ] app
- [ ] apps
- [ ] appstores
- [ ] carts
- [ ] configuration
- [ ] countries
- [ ] coupon
- [ ] cpanel
- [ ] crons
- [ ] currencies
- [ ] customer
- [ ] customers
- [ ] customfield
- [ ] emailtemplate
- [ ] eupdates
- [ ] filtergroup
- [ ] geozone
- [ ] inventories
- [ ] invoicetemplate
- [ ] length
- [ ] manufacturers
- [ ] option
- [ ] order
- [ ] orders
- [ ] orderstatuses
- [ ] payments
- [ ] postconfig
- [ ] productbase
- [ ] product
- [ ] products
- [ ] queues
- [ ] report
- [ ] reports
- [ ] shippings
- [ ] shippingtroubles
- [ ] taxprofile
- [ ] taxrate
- [ ] vendors
- [ ] voucher
- [ ] weights
- [ ] zones

Other admin
- [ ] models/fields
- [ ] models/behaviors
- [ ] helpers
- [ ] library

Site models/views/controllers
- [ ] carts
- [ ] checkout
- [ ] myprofile
- [ ] product
- [ ] products
- [ ] producttags
- [ ] vendor

Admin modules
- [ ] chart
- [ ] menu
- [ ] orders
- [ ] stats
- [ ] stats_mini

Site modules
- [ ] cart
- [ ] currency

Content plugins
- [ ] j2store

Finder plugins
- [ ] j2store

Installer plugins
- [ ] j2store

j2store plugins
- [ ] app-bootstrap3
- [ ] app-bootstrap4
- [ ] app-bootstrap5
- [ ] app_currencyupdater
- [ ] app_diagnostics
- [ ] app_flexivariable
- [ ] app_localization_data
- [ ] app_schemaproducts
- [ ] payment_banktransfer
- [ ] payment_cash
- [ ] payment_moneyorder
- [ ] payment_paypal
- [ ] payment_sagepayform
- [ ] report_itemised
- [ ] report_products
- [ ] shipping_free
- [ ] shipping_standard

search plugins
- [ ] j2store

system plugins
- [ ] j2canonical
- [ ] j2pagecache
- [ ] j2store

user plugins
- [ ] j2userregister

**Comment by brianteeman** [comment]
quick note for anyone who may come across this in the future.

the blank index.html was placed in each folder to prevent a directory index being displayed. As its now the norm for apache to be configured with noindex this is no longer required so the file can be removed.

There is however a second reason for the blank index.html and that is to prevent a folder being completely empty eg /backup or /tmp as most zip/unzip tools will not reliably include empty folders

**Comment by j2commerce** [comment]
Good point, thank you for the precision, Brian.

**Comment by brianteeman** [comment]
Should all be resolved with #79
